language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "node"
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master